### PR TITLE
fix: use GITHUB_OUTPUT instead of deprecated set-output command

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
Same as https://github.com/slsa-framework/slsa-github-generator/pull/1061

- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
- https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

https://github.com/slsa-framework/slsa-github-generator/issues/1004

### CODE REVIEW

**Comment by ianlewis** [comment]
I merged #1061 but we should probably wait to merge this until [v1.2.1](https://github.com/slsa-framework/slsa-github-generator/releases/tag/v1.2.1) is released.

**Review by laurentsimon — APPROVED** [review]

**Comment by ianlewis** [comment]
@suzuki-shunsuke I think we can merge this but there is a conflict in one of the files and I can't fix it myself. Can you fix it? then we can merge.

**Comment by suzuki-shunsuke** [comment]
Sure. I'm fixing.
The action `.github/actions/secure-checkout` seems to be removed.

**Comment by ianlewis** [comment]
> Sure. I'm fixing. The action `.github/actions/secure-checkout` seems to be removed in the main branch.

Yeah, you can probably just ignore the changes there.

**Pull request merged**
