### PR TITLE
fix: require binary upload before binary download

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

This is causing me failures: https://github.com/asraa/slsa-example/actions/runs/2502778013

[build / upload-assets](https://github.com/asraa/slsa-example/runs/6901412245?check_suite_focus=true#step:2:16)
Unable to find an artifact with the name: binary-linux-amd64

This is because binary-upload is not required for the upload-assets job.

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Thanks.
Did you hit this bug inn practice?

**Comment by asraa** [comment]
Yep: This run https://github.com/asraa/slsa-example/actions/runs/2502778013

**Comment by asraa** [comment]
> unless the testing framework has some configuration to avoid the problem.

There is a testing SetEnv that does cleanup after each test run, let me see if I can update the tests here to use that
https://cs.opensource.google/go/go/+/go1.18.3:src/testing/testing.go;l=1280

**Comment by asraa** [comment]
Oh, it is between tests too :/

**Comment by laurentsimon** [comment]
> > unless the testing framework has some configuration to avoid the problem.
> 
> There is a testing SetEnv that does cleanup after each test run, let me see if I can update the tests in another PR to use that https://cs.opensource.google/go/go/+/go1.18.3:src/testing/testing.go;l=1280

Awesome!

**Pull request merged**
