### PR TITLE
fix: Don't generate TS types for verify-token

### PR DESCRIPTION
**Pull request by ianlewis**

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Good catch

**Comment by ianlewis** [comment]
k8s.io seems to be broken somehow
```
k8s.io/api/storage/v1alpha1: k8s.io/api@v0.23.5: read "https:/proxy.golang.org/@v/v0.23.5.zip": stream error: stream ID 221; INTERNAL_ERROR; received from peer
```

However it only seems to be failing on the `build-continue-no-error` job but not on others
https://github.com/slsa-framework/slsa-github-generator/actions/runs/4694783478/jobs/8323414976?pr=1991#step:2:842

**Comment by laurentsimon** [comment]
> k8s.io vanity package names seems to be broken somehow
> 
> ```
> k8s.io/api/storage/v1alpha1: k8s.io/api@v0.23.5: read "https:/proxy.golang.org/@v/v0.23.5.zip": stream error: stream ID 221; INTERNAL_ERROR; received from peer
> ```
> 
> However it only seems to be failing on the `build-continue-no-error` job but not on others https://github.com/slsa-framework/slsa-github-generator/actions/runs/4694783478/jobs/8323414976?pr=1991#step:2:842



> k8s.io vanity package names seems to be broken somehow
> 
> ```
> k8s.io/api/storage/v1alpha1: k8s.io/api@v0.23.5: read "https:/proxy.golang.org/@v/v0.23.5.zip": stream error: stream ID 221; INTERNAL_ERROR; received from peer
> ```
> 
> However it only seems to be failing on the `build-continue-no-error` job but not on others https://github.com/slsa-framework/slsa-github-generator/actions/runs/4694783478/jobs/8323414976?pr=1991#step:2:842

I've seen other errors today and I suspect it's due to GH itself. Re-running fixed the problem in other PRs

**Comment by ianlewis** [comment]
> I've seen other errors today and I suspect it's due to GH itself. Re-running fixed the problem in other PRs

I hope so. I re-ran it twice so far and it's failed consistently each time, passing on the `build` job
https://github.com/slsa-framework/slsa-github-generator/actions/runs/4694783478/jobs/8324204627?pr=1991#step:2:847

But failing on the `build-continue-no-error` job
https://github.com/slsa-framework/slsa-github-generator/actions/runs/4694783478/jobs/8324204433?pr=1991#step:2:1151

Since they basically do the same thing it makes no sense to me.

**Pull request merged**
