### PR TITLE
fix: Bump Cosign to latest v2.2.3

### PR DESCRIPTION
**Pull request by haydentherapper**
Versions of Cosign before v2.2.0 are not compatible with the latest TUF root.

Fixes https://github.com/slsa-framework/slsa-github-generator/issues/3350

# Summary

...

## Testing Process

...

## Checklist

- [ ] Review the contributing [guidelines](./../CONTRIBUTING.md)
- [ ] Add a reference to related issues in the PR description.
- [ ] Update documentation if applicable.
- [ ] Add unit tests if applicable.
- [ ] Add changes to the [CHANGELOG](./../CHANGELOG.md) if applicable.

### CODE REVIEW

**Comment by haydentherapper** [comment]
@ianlewis @laurentsimon @kpk47 This should fix the linked issue. I'm not sure if it was an intentional decision to not update Cosign though, since I see this picks up a lot of other dependency updates.

**Comment by haydentherapper** [comment]
Ah, I see this bumps to Go 1.21. Don't know if this will be an issue for you. Feel free to ping me offline to chat more.

**Review by laurentsimon — APPROVED** [review]
LGTM. Will wait till the pre-submit is fixed.

**Comment by laurentsimon** [comment]
Can you also update the cosign-installer at https://github.com/slsa-framework/slsa-github-generator/blob/b595e069f78187eaead9bac15429f87237be550a/.github/workflows/generator_container_slsa3.yml#L170?

**Comment by laurentsimon** [comment]
Thank you all for this fast turnaround!

**Comment by saisatishkarra** [comment]
@laurentsimon is there an ETA on emergency / patch release tag to  made to unblock downstream pipelines with this bumped version? #3392

**Comment by laurentsimon** [comment]
We're working on a release as P0 and we'll cut it in the next 24hr

**Comment by sgammon** [comment]
has that release happened @laurentsimon

**Comment by laurentsimon** [comment]
We're going thru the release process and testing e2e that things are working. @kpk47 is on it

**Pull request merged**
