### PR TITLE
feat: repository-username secret

### LINKED ISSUE #1347: [feature] registry-username should be a secret
**Is your feature request related to a problem? Please describe.**

The `registry-username` input of the generator_container_slsa3 workflow is declared as input which prohibits using secrets as values. The following example fails:

```yaml
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    with:
      registry-username: ${{ secrets.DOCKER_USERNAME }} # NOT ALLOWED
    secrets:
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
```

**Describe the solution you'd like**

The `registry-username` input should be a secret. Example workflow should look liks this:

```yaml
  provenance:
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_container_slsa3.yml@v1.4.0
    secrets:
      registry-username: ${{ secrets.DOCKER_USERNAME }}
      registry-password: ${{ secrets.DOCKER_PASSWORD }}
```

**Describe alternatives you've considered**

I thought about publishing slsa data in ghcr but it feels weird when everything else is in dockerhub.

**Additional context**

This is only relevant when you are NOT using ghcr to publish images.

### PR DESCRIPTION
**Pull request by ianlewis**
Fixes #1347 

This PR adds a new `registry-username` secret input. Callers must pass either the `registry-username` secret or `registry-username` input with the `registry-username` secret taking precedence.

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]

**Comment by laurentsimon** [comment]
Please add an e2e test for this new option.

**Comment by 34fathombelow** [comment]
Thank you all for your hard work, it is much appreciated.  I'd love to see this merged, this would be very useful for me.

**Comment by laurentsimon** [comment]
@ianlewis I'll let you merge and prep a release.

**Comment by ianlewis** [comment]
> Please add an e2e test for this new option.

e2e test added in https://github.com/slsa-framework/example-package/commit/9bc9afa663d15d3c0166be323571aec030a43c19

**Comment by vincentgoat** [comment]
Hi, Community
May I ask when will the release be published with this PR?

**Comment by laurentsimon** [comment]
@ianlewis is working on it this week

**Pull request merged**
