### PR TITLE
feat: Share env variables for pre-built builder binaries

### PR DESCRIPTION
**Pull request by laurentsimon**
closes https://github.com/slsa-framework/slsa-github-generator/issues/501

### CODE REVIEW

**Review by naveensrinivasan — COMMENTED** [review]
This is great! 

Including some docs would be helpful! Especially when all of this isn't compiled code( shell script and YAML)

It would be hard for someone to come and contribute.

For example, how is the VERIFIER_* everything used? What is the order of things that have to be changed to update the VERIFIER_*?  What happens when there is a bug in VERIFIFER_ which code should be fixed.

If there are existing docs, then reference to those docs within the PR would be helpful. 
 
 This is to avoid arcane knowledge.

**Comment by laurentsimon** [comment]
> This is great!
> 
> Including some docs would be helpful! Especially when all of this isn't compiled code( shell script and YAML)
> 

I've added comment next to each variable. Does it help?

**Comment by naveensrinivasan** [comment]
> > This is great!
> > Including some docs would be helpful! Especially when all of this isn't compiled code( shell script and YAML)
> 
> I've added comment next to each variable. Does it help?

Thank you! It helps!

**Comment by laurentsimon** [comment]
friendly ping for review

**Review by ianlewis — APPROVED** [review]
LGTM

**Pull request merged**
