### PR TITLE
Update release tag for v1.2.2

### PR DESCRIPTION
**Pull request by ianlewis**
#label:release v1.2.2

Signed-off-by: Ian Lewis <ianlewis@google.com>

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]

**Comment by asraa** [comment]
The references script doesn't resolve `RELEASE_TAG`... one sec

**Comment by asraa** [comment]
oops, the body contained the sign-off too :|

**Comment by laurentsimon** [comment]
> oops, the body contained the sign-off too :|

I updated the branch from @ianlewis directly

**Comment by laurentsimon** [comment]
> > oops, the body contained the sign-off too :|
> 
> I updated the branch from @ianlewis directly

still failing :(

**Comment by asraa** [comment]
I tested a fix here: https://github.com/slsa-framework/slsa-github-generator/pull/1216, see the run linked

**Comment by asraa** [comment]
Oh, looks like the manual fix might have just included the "

**Review by asraa — APPROVED** [review]

**Pull request merged**
