### PR TITLE
fix: verifier sha refs

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Not sure why this didn't trigger an error before?

Maybe wait until https://github.com/slsa-framework/slsa-verifier/pull/114/ is approved

### CODE REVIEW

**Comment by laurentsimon** [comment]
> Signed-off-by: Asra Ali [asraa@google.com](mailto:asraa@google.com)
> 
> Not sure why this didn't trigger an error before?

The latest v1.1.1 release of the builder uses version v1.1.0 of the verifier, see https://github.com/slsa-framework/slsa-github-generator/blob/d995948e8d53cc639c0d3ef69db31dbc243519c4/.github/workflows/builder_go_slsa3.yml#L30-L31

We updated the version in the workflow to v1.1.1 after that in https://github.com/slsa-framework/slsa-github-generator/pull/411, but we don't test this path in e2e tests (always compile the builder). We would have caught this problem during the release process when we test the pre-compiled verifier.

> Maybe wait until [slsa-framework/slsa-verifier#114](https://github.com/slsa-framework/slsa-verifier/pull/114) is approved

I LGTMED'd it.

The has is `f92fc4e571949c796d7709bb3f0814a733124b0155e484fad095b5ca68b4cb21` same as the one in this PR.

**Review by laurentsimon — APPROVED** [review]
Thanks!

**Comment by ianlewis** [comment]
Oh, duh. I totally forgot to do this. Thanks!

**Comment by laurentsimon** [comment]
We could have pre-submit to catch these? (`git diff ... | grep`)?

**Pull request merged**
