### PR TITLE
Request for membership

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- I would like request for membership.

My contributions https://github.com/slsa-framework/slsa-github-generator/pulls?q=is%3Apr+author%3Anaveensrinivasan

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@laurentsimon I don't know much of TS to contribute to actions. What other feature can I contribute?

**Comment by laurentsimon** [comment]
Any other existing issues maybe?

**Comment by naveensrinivasan** [comment]
> Any other existing issues maybe?

Took up the feature as it was discussed and implemented it  https://github.com/slsa-framework/slsa-github-generator/pull/546

**Comment by ianlewis** [comment]
Trying to summarize what we want to set as requirements and what roles we are going to grant based on previous discussion.
https://github.com/slsa-framework/slsa/issues/403

I think we want to start by giving Naveen a "contributor" role that is similar to a "[reviewer](https://github.com/kubernetes/community/blob/master/community-membership.md#reviewer)" role in Kubernetes. We can adjust 
 or migrate once we have a more solid contributor ladder.

## Requirements

- [x] Reviewed 10 PRs
   - https://github.com/slsa-framework/slsa-github-generator/pulls?q=is%3Apr+reviewed-by%3Anaveensrinivasan
   - 15 total reviewed so far
- [x] 1 new "feature"
  - https://github.com/slsa-framework/slsa-github-generator/pull/546
- [x] Regular contribution for 30 days
  - Earliest PR is Jun 23 (33 days ago) (https://github.com/slsa-framework/slsa-github-generator/pull/351)
  - Regular PRs created: https://github.com/slsa-framework/slsa-github-generator/pulls?q=is%3Apr+author%3Anaveensrinivasan
  - 12 PRs merged so far
- [x] Regular feedback on discussion topics in issues/slack
  - Author: https://github.com/slsa-framework/slsa-github-generator/issues?q=is%3Aissue+author%3Anaveensrinivasan
  - Commenter: https://github.com/slsa-framework/slsa-github-generator/issues?q=is%3Aissue+commenter%3Anaveensrinivasan
  - Total 4 issues so far

## Responsibilities and privileges

- [ ] "[read and triage](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization#permissions-for-each-role)" access to the slsa-github-generator repository.
- [ ] Added to CODEOWNERS file
- [ ] Expected to help review PRs and address bugs related to area of expertise

@laurentsimon Does this look good? If so please approve the PR (I think we should have both our approvals on this one).

**Review by ianlewis — APPROVED** [review]

**Review by laurentsimon — APPROVED** [review]
LGTM

**Comment by ianlewis** [comment]
Hmm, the CODEOWNERS file complains that Naveen doesn't have write access to the repository, but the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) say you only need read access as a user.

**Comment by ianlewis** [comment]
> Hmm, the CODEOWNERS file complains that Naveen doesn't have write access to the repository, but the [docs](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) say you only need read access as a user.

It seems ok, it just doesn't add Naveen to new PRs as a reviewer. Maybe it only starts working once Naveen accepts the invitation?

**Pull request merged**
