### PR TITLE
docs: Add section about JReleaser in doc

### PR DESCRIPTION
**Pull request by aalmiray**
As suggested at https://github.com/jreleaser/jreleaser/discussions/1334

JReleaser is a release tool similarly as GoReleaser but supports more languages. The project itself uses a workflow as described in this PR to provide provenance.

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Thank you!

**Comment by laurentsimon** [comment]
You will need to run 
```
$ npm install markdown-toc
$ make markdown-toc
``` 

to fix the markdown pre-submit.

**Comment by aalmiray** [comment]
Fixed lint issues and commit title.

**Comment by aalmiray** [comment]
Updated PR title as well.

**Comment by laurentsimon** [comment]
@aalmiray shameless plug. We have beta support for https://github.com/slsa-framework/slsa-github-generator/milestone/11, which lets GitHub Action be wrapped into a SLSA3 compliant builder. That would allow your users to call a JReleaser builder (thru a reusable workflow) without calling our generator. Let me know if that sounds interesting. I'd be happy to show you a demo

**Comment by aalmiray** [comment]
@laurentsimon Oh that sounds interesting. Yes, I'd like to find out more.

**Comment by laurentsimon** [comment]
What's a good way to get in touch? We have a design doc (I can share with you), and several integrations (anchor's sbom-action, npm) I can demo.

**Comment by aalmiray** [comment]
Perhaps a zoom meeting? I've got time Wednesday & Thursday this week. I'm at GMT+2.

**Comment by laurentsimon** [comment]
I'm in PST time , which is GMT-8 I think. I've had issue presenting in zoom in the past. But please send me an invite, I will add a GVC link to it - my email is <my-github-id> AT google.com

**Pull request merged**
