### PR TITLE
feat: Add BYOB Move builder

### PR DESCRIPTION
**Pull request by daoauth**
# Summary

Adds a BYOB Move builder.

Move is a programming language developed by Facebook (now Meta) for the Libra blockchain project, which was later rebranded as Diem. Designed specifically for blockchain development, Move focuses on providing a secure and flexible framework for smart contracts and other blockchain operations.

We are currently working on a project to implement blockchain smart contracts, using the Supply Chain Levels for Software Artifacts (SLSA) framework.

https://github.com/move-language
https://move-language.github.io/move/
https://docs.zktx.io/slsa/

## Checklist

- [ ] Review the contributing [guidelines](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
- [ ] Add a reference to related issues in the PR description.
- [ ] Update documentation if applicable.
- [ ] Add unit tests if applicable.
- [ ] Add changes to the [CHANGELOG](https://github.com/slsa-framework/slsa-github-generator/blob/main/CHANGELOG.md) if applicable.

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
Welcome to SLSA. Have you been able to test this in any way? Please write that out in the PR description. Can you have an additional reviewer from your community take a look?

And have you already considered using the [generic](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md) generator?

**Comment by ianlewis** [comment]
@daoauth Thanks for doing some work on this! this is really neat.

Though, I think that, in general, we would like for other projects to use the [BYOB system](https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md) but maintain the workflows in their own separate repositories so that we don't have an explosion of workflows being maintained out of this one repo.

**Comment by daoauth** [comment]
> @daoauth Thanks for doing some work on this! this is really neat.
> 
> Though, I think that, in general, we would like for other projects to use the [BYOB system](https://github.com/slsa-framework/slsa-github-generator/blob/main/BYOB.md) but maintain the workflows in their own separate repositories so that we don't have an explosion of workflows being maintained out of this one repo.

Hi @ianlewis 

Thanks for your feedback and support. I understand the importance of managing workflows efficiently. However, we believe that keeping workflows within this repository greatly simplifies the development process and collaboration.

The Move language, originally developed by Facebook, is now used by different chains such as Aptos and Sui, each with their own compiler tailored to their specific chain. To maintain neutrality and serve as a public good, and to ensure consistency and reliability as a common tool in the Move ecosystem, we believe it is best to keep the workflows in this repository.

Could we please keep and maintain our workflows in this repository?

Thank you very much.

**Comment by daoauth** [comment]
> Welcome to SLSA. Have you been able to test this in any way? Please write that out in the PR description. Can you have an additional reviewer from your community take a look?
> 
> And have you already considered using the [generic](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md) generator?

Thank you for the warm welcome.

I will modify the implementation to use the generic generator. Partial testing has been done so far. Comprehensive testing will be conducted once the development of the code deployment part to the actual blockchain is complete.

Thank you very much.

**Comment by daoauth** [comment]
Thank you for the warm welcome and guidance. I have reviewed the generic generator as @ramonpetgrave64 suggested and understand the reasons for its use.

Therefore, in line with @ianlewis suggestion, could we close this PR and open a new one to add the Move language guide to [this document](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md)?

We are also considering adding other blockchain languages in the future.

Thank you very much.

**Comment by ramonpetgrave64** [comment]
Feel free to open another PR with your suggestions.

**Pull request closed without merging**
