### PR TITLE
✨ Allow nil OIDC client

### PR DESCRIPTION
**Pull request by laurentsimon**
Allow nil OIDC client. This is needed to implement some level of e2e pre-submits, see https://github.com/slsa-framework/slsa-github-generator-go/pull/73

On pull request triggers, the `id-token` permissions is set to `read` so we cannot use OIDC features. (`write` is needed)

We still want to have pre-submit e2e tests the the extent possible: we will not sign the provenance. Full e2e verification including signature verification is run daily in https://github.com/slsa-framework/example-package/tree/main/.github/workflows and progress tracked in https://github.com/slsa-framework/slsa-github-generator-go/issues/3#issuecomment-1097455581.

### CODE REVIEW

**Review by ianlewis — APPROVED** [review]
LGTM. Thanks! Sorry for not getting to this earlier.

**Comment by laurentsimon** [comment]
> LGTM. Thanks! Sorry for not getting to this earlier.

I sent it just a few hours ago, so LGTM was pretty fast

**Comment by ianlewis** [comment]
> I sent it just a few hours ago, so LGTM was pretty fast

Yeah, but you requested this change and I didn't make it myself. That's what I meant ;)

**Comment by laurentsimon** [comment]
np

**Pull request merged**
