### PR TITLE
docs: Update Node.js builder docs

### PR DESCRIPTION
**Pull request by ianlewis**
- Adds a "known issues" section.
- Adds instructions on how to custom publish without using the `publish` action.

Related #2322

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
Also update https://github.com/slsa-framework/slsa-github-generator#builders to say nodejs is now GA

**Comment by ianlewis** [comment]
We haven't GAed the Node.js builder yet

**Comment by laurentsimon** [comment]
> We haven't GAed the Node.js builder yet

I thought the release was to GA it...

**Comment by ianlewis** [comment]
> > We haven't GAed the Node.js builder yet
> 
> I thought the release was to GA it...

This release is to fix some blocking bugs.

**Pull request merged**
