### PR TITLE
docs: Add Atsign-Foundation NoPorts to the Hall of Fame

### PR DESCRIPTION
**Pull request by cpswan**
# Summary

We're using generators for our Dart and Python release artifacts e.g.
https://github.com/atsign-foundation/noports/releases/tag/v5.2.1-rc1
https://github.com/atsign-foundation/noports/releases/tag/p0.4.9

## Testing Process

N/A - docs update

## Checklist

- [x] Review the contributing [guidelines](https://github.com/slsa-framework/slsa-github-generator/blob/main/CONTRIBUTING.md)
- [ ] Add a reference to related issues in the PR description.
- [x] Update documentation if applicable.
- [ ] Add unit tests if applicable.
- [ ] Add changes to the [CHANGELOG](https://github.com/slsa-framework/slsa-github-generator/blob/main/CHANGELOG.md) if applicable.

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
Welcome! You mentioned in #3617 to make this a multiline. I'd accept that. But just FYI, the "rich diff" view on github also makes the change clear. https://github.com/slsa-framework/slsa-github-generator/pull/3616/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by cpswan** [comment]
@ramonpetgrave64 rather than a new PR are you OK with me pushing the multiline version for #3617 to this branch, in which case I'll convert this to draft for now and set it back when ready.

Also any thoughts on ordering: alphabetic or leave things how they are?

**Comment by ramonpetgrave64** [comment]
Let's keep the order, but I'm okay with either the multiline or single line. Up to you.

**Review by ramonpetgrave64 — APPROVED** [review]

**Review by ramonpetgrave64 — APPROVED** [review]

**Comment by ramonpetgrave64** [comment]
Looks good, but one more thing. You'll have to signoff on your commits. see the details on the DCO check.

**Comment by cpswan** [comment]
@ramonpetgrave64 doh! Signoff now added to that last commit.

**Pull request merged**
