### PR TITLE
feat: draft release support

### LINKED ISSUE #1476: [feature] support creating a draft release
The Go builder and generic generator use `softprops/action-gh-release` to create releases. We should support setting the `draft` flag so that users can create draft releases.

Related: https://github.com/sigstore/helm-sigstore/pull/111

### PR DESCRIPTION
**Pull request by developer-guy**
I started with the generic builder and will continue with the others as well if you accept the solution:

Fixes #1476 

I tried that in osv-scanner project and it worked: 
* Job: _https://github.com/developer-guy/osv-scanner/actions/runs/4536204956/jobs/7992687991_
* Release: _https://github.com/developer-guy/osv-scanner/releases/tag/untagged-5bf09e3accd2794d0d10_

PTAL @laurentsimon @asraa @ianlewis

### CODE REVIEW

**Comment by ianlewis** [comment]
Thanks! Can you:
- [ ] Add `draft-release` to the [Go builder](https://github.com/slsa-framework/slsa-github-generator/blob/main/.github/workflows/builder_go_slsa3.yml)?
- [ ] Add `draft-release` to the docs for both the generic generator and Go builder?
- [ ] Add a note to the `CHANGELOG.md`?

**Comment by developer-guy** [comment]
ready for review @ianlewis

**Comment by ianlewis** [comment]
Thanks! Could you add the `draft-release` input to the docs for the [generic generator](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#workflow-inputs), [docker based builder](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/docker/README.md#workflow-inputs), and [Go builder](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md#workflow-inputs) ?

We should also have a note in the [CHANGELOG.md](https://github.com/slsa-framework/slsa-github-generator/blob/main/CHANGELOG.md#v160) for the v1.6.0 release.

**Comment by developer-guy** [comment]
- [x] Add draft-release to the docs for the generic generator
- [x] Add draft-release to the docs for the Go builder?
- [x] Add draft-release to the docs for the docker-based builder?
- [x] Add a note to the CHANGELOG.md?

**Review by laurentsimon — APPROVED** [review]

**Review by ianlewis — APPROVED** [review]
Thanks!

**Pull request merged**
