### PR TITLE
fix: workingDir

### PR DESCRIPTION
**Pull request by laurentsimon**

### CODE REVIEW

**Review by ianlewis — APPROVED** [review]
Do we even use this file anywhere?

**Comment by asraa** [comment]
> Do we even use this file anywhere?

In the go presubmit!

**Comment by asraa** [comment]
I thought about filing an issue to consolidate with example-package: and just gate on whether we're running in this repository for avoiding the sig verification

**Review by asraa — APPROVED** [review]

**Comment by ianlewis** [comment]
> > Do we even use this file anywhere?
> 
> In the go presubmit!
Yeah! I found it. Searching for it on GitHub yielded zero results so I was confused initially.

Strange that this breakage got in in the first place :-/

**Pull request merged**
