### PR TITLE
update verifier version in actions

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Pending https://github.com/slsa-framework/slsa-verifier/pull/288/files

to fix https://github.com/slsa-framework/slsa-github-generator/issues/942

### CODE REVIEW

**Comment by asraa** [comment]
The hash was verified in https://github.com/slsa-framework/slsa-verifier/pull/288

**Comment by asraa** [comment]
After this: a new patch version of the builders needs to be pushed

**Review by ianlewis — APPROVED** [review]

**Review by ianlewis — APPROVED** [review]

**Comment by lukehinds** [comment]
when will a release be made with this fix?

**Comment by asraa** [comment]
> when will a release be made with this fix?

Hi! We're just about done. We're working on some fixes in the release https://github.com/slsa-framework/slsa-github-generator/issues/968, and should definitely be done by EOW if not sooner.

Thank you so much for the patience here.

**Pull request merged**
