### PR TITLE
feat: Support GCP Workload Identity authentication in the Container Generator

### LINKED ISSUE #1545: [bug] Unable to authenticate with Google Artifact Registry using Workload Identity
Originally posted by @mchmarny
https://github.com/slsa-framework/slsa-github-generator/issues/1257#issuecomment-1384431361

-----

This appears to be also failing against Artifact Registry (full trace for the above error [here](https://github.com/mchmarny/s3cme/actions/runs/3919419059/jobs/6700471398#step:5:700))

```shell
main.go:62: error during command execution: signing us-west1-docker.pkg.dev/cloudy-s3c/s3cme/s3cme@sha256:f17fc9c49e3e1cef22022332c0f55a51d60b12d7403990a6aac6564f4bbd4910: GET https://us-west1-docker.pkg.dev/v2/token?scope=repository%3Acloudy-s3c%2Fs3cme%2Fs3cme%3Apull&service=: DENIED: Permission "artifactregistry.repositories.downloadArtifacts" denied on resource "projects/cloudy-s3c/locations/us-west1/repositories/s3cme" (or it may not exist)
```

This is despite of the `cosign login` to registry being succesful in the [previous step](https://github.com/mchmarny/s3cme/actions/runs/3919419059/jobs/6700471398#step:4:62)

```shell
login to us-west1-docker.pkg.dev
auth.go:191: logged in via /home/runner/.docker/config.json
```

Also, `cosign attest` (after authentication with the same OIDC token), with the same `predicate.json` file, on the same image, works fine, so the rights of the impersonated service account for which the token was issued are correct. 

```shell
COSIGN_EXPERIMENTAL=1 cosign attest --force --predicate predicate.json --type slsaprovenance $IMG_DIGEST
```

I ended up abandoning this reusable workflow and just [used the released `slsa-github-generator`](https://github.com/mchmarny/s3cme/blob/main/.github/workflows/slsa.yaml) artifact manually (after sha verification). 

FWIW, a Go app repo template with image build/publish pipelines, SBOM, and SLSA provenance (using your `slsa-github-generator`), and OIDC, KMS and Artifact Registry is available in https://github.com/mchmarny/s3cme

### PR DESCRIPTION
**Pull request by ianlewis**
Fixes #1545

Adds special support for generating a short-lived GCP Workload Identity token for authentication with Google Artifact Registry and Google Container Registry.

Special support is needed because access tokens cannot be passed between GitHub actions jobs so users cannot generate and pass the tokens to the container generator reusable workflow themselves.

TODO:
- [x] Document the new inputs.
- [x] e2e test plan
- [x] CHANGELOG entry

Signed-off-by: Ian Lewis <ianlewis@google.com>

### CODE REVIEW

**Review by laurentsimon — APPROVED** [review]
LGTM

**Comment by ianlewis** [comment]
@laurentsimon Gonna wait a bit to merge until I get a plan in place for e2e tests.

**Comment by ianlewis** [comment]
I got access to the GCP project used for e2e tests so I'll add a new service account and Artifact registry package there.

**Comment by ianlewis** [comment]
e2e test is here:
https://github.com/slsa-framework/example-package/blob/a200c661fb1332b9b2625ea6d16210d7d7f31642/.github/workflows/e2e.container.tag.main.gcp-workload-identity.slsa3.yml

and successful run of it is here:
https://github.com/slsa-framework/example-package/actions/runs/3983397638

**Pull request merged**
