### PR TITLE
chore: v2.0.0: update tags

### PR DESCRIPTION
**Pull request by ramonpetgrave64**
#label:release v2.0.0

### CODE REVIEW

**Comment by ramonpetgrave64** [comment]
references test is failing, as expected.

https://github.com/slsa-framework/slsa-github-generator/actions/runs/8788176646/job/24115061279?pr=3583#step:4:5

```
Run ./__THIS_REPO__/.github/workflows/scripts/pre-submit.actions/references.sh
Some Actions are not referenced at main
.github/workflows/delegator_generic_slsa3.yml:        uses: slsa-framework/slsa-github-generator/.github/actions/rng@v2.0.0
.github/workflows/delegator_generic_slsa3.yml:        uses: slsa-framework/slsa-github-generator/.github/actions/verify-token@v2.0.0
.github/workflows/delegator_generic_slsa3.yml:        uses: slsa-framework/slsa-github-generator/.github/actions/secure-upload-artifact@v2.0.0
....
```

We will change the references to `main`, in a later step
https://github.com/slsa-framework/slsa-github-generator/blob/main/RELEASE.md#reference-actions-at-main

**Comment by ramonpetgrave64** [comment]
@laurentsimon

**Review by kpk47 — APPROVED** [review]

**Comment by ramonpetgrave64** [comment]
Now passing after fixing the PR description, and also closing and re-opening the PR.

https://github.com/slsa-framework/slsa-github-generator/actions/runs/8789987007/job/24120997500?pr=3583

**Comment by ramonpetgrave64** [comment]
tracking in https://github.com/slsa-framework/slsa-github-generator/issues/3576

**Pull request merged**
