### PR TITLE
test: use t.Setenv for auto cleanup 

### PR DESCRIPTION
**Pull request by asraa**
Signed-off-by: Asra Ali <asraa@google.com>

Fixes flakiness in tests, re-ran this 50 times locally in sequence with no failure.

### CODE REVIEW

**Comment by asraa** [comment]
Problem fixed: I removed parallelism from the tests that manipulate arg vars.

**Comment by laurentsimon** [comment]
> Problem fixed: I removed parallelism from the tests that manipulate env vars.

wait what? I thought I commented out all these `t.Parallel()`.

Thanks!

**Comment by laurentsimon** [comment]
> > Problem fixed: I removed parallelism from the tests that manipulate env vars.
> 
> wait what? I thought I commented out all these `t.Parallel()`.
> 
> Thanks!

ah, so there is also a call a the top of each function, I missed this one :/

**Review by laurentsimon — APPROVED** [review]

**Comment by laurentsimon** [comment]
> :/ weird.
> 
> ```
> 2022-06-15T15:26:23.6179049Z === RUN   Test_generateOutputFilename/filename_twice_unset_versions
> 2022-06-15T15:26:23.6180439Z     build_test.go:458:   any(
> 2022-06-15T15:26:23.6181010Z         - 	e"invalid filename: found character '/'",
> 2022-06-15T15:26:23.6181334Z           )
> ```
> 
> filename twice unset is taking the filename from the previous test ("invalid name with version",)

mhhh the `{{ .Tag }}` is evaluated by reading `GITHUB_REF_NAME`. Note that this variables is already set by default by GitHub. Maybe this is causing problems?

**Comment by laurentsimon** [comment]
we may need to copy the variable like we do in scorecard, e.g. https://github.com/ossf/scorecard/blob/main/checks/branch_protection_test.go#L389

**Pull request merged**
