### PR TITLE
docs: Document that actions/download-artifact@v3 must be used to download provenance

### PR DESCRIPTION
**Pull request by jkreileder**
Fixes https://github.com/slsa-framework/slsa-github-generator/issues/3066

### CODE REVIEW

**Comment by ianlewis** [comment]
Could you add this under the "Known Issues" section of the READMEs? (If there isn't one then you can add it)

**Review by laurentsimon — APPROVED** [review]
Thanks!

I'll wait til you have addressed @ianlewis's comment to merge.

**Comment by jkreileder** [comment]
I've moved the notes and updated the tocs.

**Comment by ianlewis** [comment]
Thanks!

**Pull request merged**
